version: '3'
services:
  nhl_notify:
    build: .
    environment:
      - LIGHT_ID=5
      - TEAM_FILTERS=New_Jersey_Devils
      - BRIDGE_IP=192.168.1.157
      - BRIDGE_USER=Q-SvabD65raZTo9R65pMdNJeSc4itnZ3Y5jwrI98
      - SPOTIFY_ALBUM=spotify:album:1gsyJWUvwjnsNgYUxpOfLR
      - SPOTIFY_SONG_NUM=7
      - SPOTIFY_TOKEN=AQDpCnqmlEGo48mwtJokRJBD4SdKDBxubyj1CLFvAuIDgGNbplfP627EXfUyJ8pmrWw1rnTukCq2eAVi5uCs3gSQy4PWDqnKa0yUBtGIC-ZUIy_G-Er6kG5oYdKmIRLd-9oz8A
      - SPOTIFY_DEVICE_ID=8a802d0bfa7189b17a07de69df207f37451e7d3b
    command: ["python", "/app/notifier.py", "test_notify"]